from Grammar import Grammar

grammar = Grammar("gram2")

grammar.setNonTerminals("A")
grammar.setNonTerminals("B")
grammar.setNonTerminals("C")
grammar.setNonTerminals("D")
grammar.setNonTerminals("E")
grammar.setNonTerminals("F")
grammar.setNonTerminals("G")
grammar.setNonTerminals("H")
grammar.setNonTerminals("I")

grammar.setTerminals("c")
grammar.setTerminals("v")

grammar.setInitialNT("A")

grammar.setProductions("A>c B | A>v G")
# grammar.setProductions("A>v G")
grammar.setProductions("B>c C | B>v D | B>epsilon")
# grammar.setProductions("B>v D")
# grammar.setProductions("B>epsilon")
grammar.setProductions("C>v G | C>c B")
# grammar.setProductions("C>c B")
grammar.setProductions("D>v E | D>c C | D>epsilon")
# grammar.setProductions("D>c C")
# grammar.setProductions("D>epsilon")
grammar.setProductions("E>v F | E>c C | E>epsilon")
# grammar.setProductions("E>c C")
# grammar.setProductions("E>epsilon")
grammar.setProductions("F>epsilon | F>c C")
# grammar.setProductions("F>c C")
grammar.setProductions("G>v H | G>c B")
# grammar.setProductions("G>c B")
grammar.setProductions("H>v I | H>c B")
# grammar.setProductions("H>c B")
grammar.setProductions("I>c B")

grammar.evaluateString("vvvcvvvcvc")