from Grammar import Grammar

grammar = Grammar("gram2")

grammar.setNonTerminals("A")
grammar.setNonTerminals("B")
grammar.setNonTerminals("C")
grammar.setNonTerminals("D")
grammar.setNonTerminals("E")
grammar.setNonTerminals("F")
grammar.setNonTerminals("G")
grammar.setNonTerminals("H")
grammar.setNonTerminals("I")

grammar.setTerminals("c")
grammar.setTerminals("v")

grammar.setProductions("A>c B")
grammar.setProductions("A>v G")
grammar.setProductions("B>c C")
grammar.setProductions("B>v D")
grammar.setProductions("B>epsilon")
grammar.setProductions("C>v G")
grammar.setProductions("C>c B")
grammar.setProductions("D>v E")
grammar.setProductions("D>c C")
grammar.setProductions("D>epsilon")
grammar.setProductions("E>v F")
grammar.setProductions("E>c C")
grammar.setProductions("E>epsilon")
grammar.setProductions("F>epsilon")
grammar.setProductions("F>c C")
grammar.setProductions("G>v H")
grammar.setProductions("G>c B")
grammar.setProductions("H>v I")
grammar.setProductions("H>c B")
grammar.setProductions("I>c B")
